//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolNameGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoolNameGenerator.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm Terminated Successful !.
        /// </summary>
        public static string AlgorithmTerminatedSuccessful {
            get {
                return ResourceManager.GetString("AlgorithmTerminatedSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument MinValue must be less than MaxValue.
        /// </summary>
        public static string Argument_MinMaxValue {
            get {
                return ResourceManager.GetString("Argument_MinMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} parameter is null!.
        /// </summary>
        public static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Argument out Of range and must be positive.
        /// </summary>
        public static string ArgumentOutOfRange_MustBePositive {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Chromosome.
        /// </summary>
        public static string BestChromosome {
            get {
                return ResourceManager.GetString("BestChromosome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Name Generator (PGA).
        /// </summary>
        public static string CoolNameGenerator_PGA {
            get {
                return ResourceManager.GetString("CoolNameGenerator_PGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossover.
        /// </summary>
        public static string Crossover {
            get {
                return ResourceManager.GetString("Crossover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display result realtime.
        /// </summary>
        public static string DisplayRealtime {
            get {
                return ResourceManager.GetString("DisplayRealtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Files (*.txt, *.csv)|*.txt;*.csv.
        /// </summary>
        public static string FilterWordFiles {
            get {
                return ResourceManager.GetString("FilterWordFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian To Finglish Converter.
        /// </summary>
        public static string FinglishConverter {
            get {
                return ResourceManager.GetString("FinglishConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finglish Name.
        /// </summary>
        public static string FinglishName {
            get {
                return ResourceManager.GetString("FinglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness.
        /// </summary>
        public static string Fitness {
            get {
                return ResourceManager.GetString("Fitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation.
        /// </summary>
        public static string Generation {
            get {
                return ResourceManager.GetString("Generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A generation should have at least 2 chromosomes..
        /// </summary>
        public static string generation_should_have_at_least_2_chromosomes {
            get {
                return ResourceManager.GetString("generation_should_have_at_least_2_chromosomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFinglish Exception!.
        /// </summary>
        public static string GetFinglish_Exception {
            get {
                return ResourceManager.GetString("GetFinglish_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has hyphen -.
        /// </summary>
        public static string HasHyphen {
            get {
                return ResourceManager.GetString("HasHyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has numeric letters.
        /// </summary>
        public static string HasNumeric {
            get {
                return ResourceManager.GetString("HasNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Persian Words.
        /// </summary>
        public static string ImportPersianWords {
            get {
                return ResourceManager.GetString("ImportPersianWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum size for a population should be equal or greater than minimum size..
        /// </summary>
        public static string maximum_size_for_a_population_should_be_equal_or_greater_than_minimum_size {
            get {
                return ResourceManager.GetString("maximum_size_for_a_population_should_be_equal_or_greater_than_minimum_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum size for a population is 2 chromosomes..
        /// </summary>
        public static string minimum_size_for_a_population_is_2_chromosomes {
            get {
                return ResourceManager.GetString("minimum_size_for_a_population_is_2_chromosomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutation.
        /// </summary>
        public static string Mutation {
            get {
                return ResourceManager.GetString("Mutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Persian Words File.
        /// </summary>
        public static string OpenPersianFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenPersianFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} index must be less than {1} values.
        /// </summary>
        public static string OutOfRangeException_indexMustLessThan {
            get {
                return ResourceManager.GetString("OutOfRangeException_indexMustLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Process.
        /// </summary>
        public static string ParallelProcess {
            get {
                return ResourceManager.GetString("ParallelProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian Name.
        /// </summary>
        public static string PersianName {
            get {
                return ResourceManager.GetString("PersianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Genetic Algorithm Toolbox.
        /// </summary>
        public static string PGAToolbox {
            get {
                return ResourceManager.GetString("PGAToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population Size.
        /// </summary>
        public static string PopulationSize {
            get {
                return ResourceManager.GetString("PopulationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Finglish Words File.
        /// </summary>
        public static string SaveFinglishWordsFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveFinglishWordsFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Result.
        /// </summary>
        public static string SaveResult {
            get {
                return ResourceManager.GetString("SaveResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Generator.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument must be have more than 2 length..
        /// </summary>
        public static string The_argument_must_be_have_more_than_2_length {
            get {
                return ResourceManager.GetString("The_argument_must_be_have_more_than_2_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Evolving.
        /// </summary>
        public static string TimeEvolving {
            get {
                return ResourceManager.GetString("TimeEvolving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        public static string Toolbox {
            get {
                return ResourceManager.GetString("Toolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Length.
        /// </summary>
        public static string WordLen {
            get {
                return ResourceManager.GetString("WordLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word maximum length.
        /// </summary>
        public static string WordMaxLen {
            get {
                return ResourceManager.GetString("WordMaxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word minimum length.
        /// </summary>
        public static string WordMinLen {
            get {
                return ResourceManager.GetString("WordMinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Progress Counter.
        /// </summary>
        public static string WordProgressCounter {
            get {
                return ResourceManager.GetString("WordProgressCounter", resourceCulture);
            }
        }
    }
}
